server:
  port: 3002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: "000000"
      url: jdbc:mysql://localhost:3306/zhangfx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
